# Experiments

In [11]:
%reload_ext autoreload
%autoreload 2

## The Structure of `points_{i}.json`

In [2]:
from pprint import pprint
import json

# load data
points_json_path = '../data/07_03_2019/extrinsic_calibration/points/points_1.json'
with open(points_json_path) as f:
    points_data = json.load(f)
    
pprint(points_data.keys())

dict_keys(['created_timestamp', 'board_shape', 'board_edge_len', 'camera_resolution', 'points'])


In [3]:
pprint(points_data['camera_resolution'])
pprint(points_data['board_shape'])
pprint(points_data['board_edge_len'])
pprint(points_data['created_timestamp'])

[2704, 1520]
[9, 6]
0.088
'2020-07-13 02:14:37.337370'


In [4]:
import numpy as np

for img_name, v in points_data['points'].items():
    points_a_img = np.array(v)
    pprint('{}: {}'.format(img_name, points_a_img.shape))
    pprint(points_a_img)
    break

'img00001.jpg: (9, 6, 2)'
array([[[1750.86230469,  734.2477417 ],
        [1766.11193848,  737.40435791],
        [1783.21447754,  739.38000488],
        [1798.68786621,  740.45635986],
        [1813.7421875 ,  742.74676514],
        [1830.02331543,  745.2467041 ]],

       [[1845.24279785,  747.25390625],
        [1861.40722656,  748.89904785],
        [1876.36157227,  751.03137207],
        [1748.76696777,  751.25909424],
        [1765.60778809,  753.50256348],
        [1781.38659668,  754.59082031]],

       [[1795.54125977,  756.25024414],
        [1812.28613281,  758.7276001 ],
        [1826.62365723,  760.50897217],
        [1842.83178711,  762.61260986],
        [1857.6920166 ,  764.75292969],
        [1872.63354492,  766.91711426]],

       [[1746.54577637,  766.96899414],
        [1761.67858887,  769.56994629],
        [1777.79418945,  771.30657959],
        [1793.64099121,  773.31744385],
        [1809.29553223,  775.12854004],
        [1825.25305176,  777.14709473]],

      

## The Structure of `scene.json`

In [44]:
from pprint import pprint
import json

# load data
points_json_path = '../data/27_02_2019/extrinsic_calibration/scene.json'
with open(points_json_path) as f:
    points_data = json.load(f)
    
pprint(points_data.keys())

dict_keys(['created_timestamp', 'camera_resolution', 'cameras'])


In [45]:
pprint(points_data['camera_resolution'])
pprint(points_data['cameras'])

[2704, 1520]
[{'d': [[0.03743898455870094],
        [0.04784376818211986],
        [-0.03758546926131943],
        [0.010781487471488252]],
  'k': [[1239.734301643185, 0.0, 1345.6656873020534],
        [0.0, 1238.6767415364864, 772.857231264526],
        [0.0, 0.0, 1.0]],
  'r': [[1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]],
  't': [[0.0], [0.0], [0.0]]},
 {'d': [[0.03743898455870094],
        [0.04784376818211986],
        [-0.03758546926131943],
        [0.010781487471488252]],
  'k': [[1239.734301643185, 0.0, 1345.6656873020534],
        [0.0, 1238.6767415364864, 772.857231264526],
        [0.0, 0.0, 1.0]],
  'r': [[0.9719820679700437, 0.2225043565264481, 0.07578041218829916],
        [0.08228589145252886, -0.020100054232543067, -0.9964060517117063],
        [-0.2201814969804227, 0.9747244734521648, -0.03784586160810736]],
  't': [[-6.208764337856968], [0.04808523944230497], [-0.6165180276606337]]},
 {'d': [[0.03743898455870094],
        [0.04784376818211986],
        [-0.037

## The Structure of `scene_sba.json`

In [2]:
from pprint import pprint
import json

# load data
scene_sba_json_path = '../data/27_02_2019/extrinsic_calibration/scene_sba.json'
with open(scene_sba_json_path) as f:
    scene_sba = json.load(f)
    
pprint(scene_sba.keys())

dict_keys(['created_timestamp', 'camera_resolution', 'cameras'])


In [4]:
pprint(scene_sba['cameras'])

[{'d': [[0.03743898455870094],
        [0.04784376818211986],
        [-0.03758546926131943],
        [0.010781487471488252]],
  'k': [[1239.734301643185, 0.0, 1345.6656873020534],
        [0.0, 1238.6767415364864, 772.857231264526],
        [0.0, 0.0, 1.0]],
  'r': [[1.0, -5.1086308649931915e-15, 3.262779708392339e-14],
        [3.2627797083923404e-14, 2.7257675990579326e-15, -1.0],
        [5.1086308649931e-15, 1.0, 2.7257675990580994e-15]],
  't': [[0.0], [2.0765062910099078e-15], [7.966417435842415e-16]]},
 {'d': [[0.03743898455870094],
        [0.04784376818211986],
        [-0.03758546926131943],
        [0.010781487471488252]],
  'k': [[1239.734301643185, 0.0, 1345.6656873020534],
        [0.0, 1238.6767415364864, 772.857231264526],
        [0.0, 0.0, 1.0]],
  'r': [[0.9719820679700436, 0.22250435652644807, 0.07578041218829917],
        [0.08228589145252883, -0.020100054232542994, -0.9964060517117062],
        [-0.22018149698042266, 0.9747244734521647, -0.037845861608107254]],
 

## Parewise-Extrinsic Calibration with Dummy Scene Data

In [3]:
import os
import sys
import glob
from pprint import pprint
import numpy as np
import cv2
sys.path.append('./Calib')
from calib import calib, app


DATA_ROOT_DIR = '../data'
CONFIG_DIR = os.path.abspath('../configs')
INTRINSIC_DATA_DIR = os.path.join(DATA_ROOT_DIR, 'intrinsic_calibration')


NUM_CAMERA = 6

# generate dir paths including extrinsic calibration videos
day_paths = glob.glob(os.path.join(DATA_ROOT_DIR, '??_??_20??'))
extrinsic_data_paths = []
for day_path in day_paths:
    extrinsic_data_paths.append(
        os.path.join(day_path, 'extrinsic_calibration')
    )
# pprint(extrinsic_data_paths)

extrinsic_data_path = extrinsic_data_paths[2]
# print(extrinsic_data_path)


# Get paths of the calibration videos
calib_video_path = os.path.join(extrinsic_data_path, 'videos')
calib_vids = sorted(glob.glob(os.path.join(calib_video_path, '*.mp4')))
assert len(calib_vids) == NUM_CAMERA, 'expect {} camera videos but the number of videos is {}'.format(
    NUM_CAMERA, len(calib_vids)
)
# pprint(calib_vids)



camera_fpaths = [os.path.join(INTRINSIC_DATA_DIR, "camera.json") for _ in range(NUM_CAMERA)]
points_fpaths = [os.path.join(extrinsic_data_path, f"points/points_{i+1}.json") for i in range(NUM_CAMERA)]
scene_fpath = os.path.join(extrinsic_data_path, "scene.json")
app.calibrate_fisheye_extrinsics_pairwise(
    camera_fpaths, points_fpaths, 
    out_fpath=scene_fpath,
    dummy_scene_path=os.path.join(CONFIG_DIR, 'dummy_scene.json'),
    start_camera_i=0
)

No corresponding points between img_pts at index 2 and 3
Instead of that dummy_R[3] and dummy_T[3] were used
[array([[ 1.,  0.,  0.],
       [ 0.,  0., -1.],
       [ 0.,  1.,  0.]], dtype=float32),
 array([[ 0.97198207,  0.22250436,  0.07578041],
       [ 0.08228589, -0.02010005, -0.99640605],
       [-0.2201815 ,  0.97472447, -0.03784586]]),
 array([[ 0.8363196 ,  0.54274462,  0.07744554],
       [ 0.11153586, -0.03012963, -0.99330356],
       [-0.53677675,  0.83935719, -0.08573349]]),
 array([[-0.9940601 , -0.10122479,  0.03997581],
       [-0.04360602,  0.03390697, -0.99847325],
       [ 0.09971478, -0.9942856 , -0.03811958]]),
 array([[-0.96050261, -0.27735143,  0.02260348],
       [-0.03833284,  0.0514216 , -0.99794109],
       [ 0.27561808, -0.95939148, -0.06002225]]),
 array([[-0.76325453, -0.64436712,  0.04726022],
       [-0.09478817,  0.03932043, -0.99472062],
       [ 0.63910697, -0.76370473, -0.09108988]])]
[array([[0.],
       [0.],
       [0.]], dtype=float32),
 array([[

SystemExit: 1

## SBA with Pre-Difined Points

In [43]:
import os
import sys
import glob
from pprint import pprint
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
import cv2
sys.path.append('./Calib')
from calib import calib, app


DATA_ROOT_DIR = '../data'
CONFIG_DIR = os.path.abspath('../configs')
INTRINSIC_DATA_DIR = os.path.join(DATA_ROOT_DIR, 'intrinsic_calibration')


NUM_CAMERA = 6

# generate dir paths including extrinsic calibration videos
day_paths = glob.glob(os.path.join(DATA_ROOT_DIR, '??_??_20??'))
extrinsic_data_paths = []
for day_path in day_paths:
    extrinsic_data_paths.append(
        os.path.join(day_path, 'extrinsic_calibration')
    )
# pprint(extrinsic_data_paths)

extrinsic_data_path = extrinsic_data_paths[2]
# print(extrinsic_data_path)


# Get paths of the calibration videos
calib_video_path = os.path.join(extrinsic_data_path, 'videos')
calib_vids = sorted(glob.glob(os.path.join(calib_video_path, '*.mp4')))
assert len(calib_vids) == NUM_CAMERA, 'expect {} camera videos but the number of videos is {}'.format(
    NUM_CAMERA, len(calib_vids)
)
# pprint(calib_vids)



camera_fpaths = [os.path.join(INTRINSIC_DATA_DIR, "camera.json") for _ in range(NUM_CAMERA)]
points_fpaths = [os.path.join(extrinsic_data_path, f"points/points_{i+1}.json") for i in range(NUM_CAMERA)]
scene_fpath = os.path.join(extrinsic_data_path, "scene.json")



defined_point_fpath = os.path.join(extrinsic_data_path, f"defined_points/defined_points.json")
scene_sba_fpath = os.path.join(extrinsic_data_path, "scene_sba.json")
res = app.sba_board_points_fisheye(
    scene_fpath, points_fpaths, defined_point_fpath,
    out_fpath=scene_sba_fpath
)
print(f"Before: mean: {np.mean(res['before'])}, std: {np.std(res['before'])}")
print(f"After: mean: {np.mean(res['after'])}, std: {np.std(res['after'])}")

   Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality   
       0              1         5.7423e+03                                    4.12e+05    
       1             19         5.7423e+03      4.02e-02       8.13e+00       4.12e+05    
       2             21         5.7373e+03      4.99e+00       5.04e-01       4.12e+05    
       3             22         5.7273e+03      9.98e+00       1.15e-01       4.12e+05    
       4             23         5.7227e+03      4.62e+00       3.30e-01       4.12e+05    
       5             24         5.7201e+03      2.58e+00       4.98e-02       4.12e+05    
       6             25         5.7164e+03      3.73e+00       6.11e-02       4.12e+05    
       7             26         5.7133e+03      3.11e+00       6.63e-02       4.12e+05    
       8             27         5.7106e+03      2.70e+00       7.19e-02       4.13e+05    
       9             28         5.7095e+03      1.12e+00       6.71e-02       4.12e+05    